[phases.setup]
nixPkgs = [
    "php83",
    "php83Extensions.imagick",
    "php83Extensions.pdo_pgsql",
    "php83Extensions.exif",
    "imagemagick",
    "libjpeg",
    "libpng",
    "zlib",
    "pngquant",
    "jpegoptim"
]

[phases.build]
dependsOn = ["setup"]
cmds = [
    "COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader --no-interaction",
    "npm install && npm run build"
]
